# Site settings
title: Course Website
subtitle: Title of the Course
description: |
    I wil come up with a description later.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aaronhangzhou.xicp.net:4000" # the base hostname & protocol for your site
syllabus: "https://github.com/svmiller/svm-r-markdown-templates/blob/master/syllabus-example/svm-rmarkdown-syllabus-example.pdf"
githubdir: "jiajunmao/course-website"

# Author/user information
email: aaron@investarchina.com
twitter_username: aaronmao
github_username:  jiajunmao
authorurl: "http://svmiller.com"
address: |
    Department of Political Science
    232 Brackett Hall
    Clemson, SC 29634-1354


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
