# Site settings
title: Course Website for CEA/CS
subtitle: Introduction to Object-Oriented Programming in Java
description: |
    I will think of an description later.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://teaching.investarchina.com # the base hostname & protocol for your site
syllabus: "https://github.com/svmiller/svm-r-markdown-templates/blob/master/syllabus-example/svm-rmarkdown-syllabus-example.pdf"
githubdir: "jiajunmao/course-website"

# Author/user information
email: aaron@investarchina.com
github_username:  jiajunmao
authorurl: "http://jiajunmao.github.io"
address: |
    Department of Political Science
    232 Brackett Hall
    Clemson, SC 29634-1354


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
